package org.openroadcode.androidbridge;

import android.Manifest;
import android.app.Activity;
import android.bluetooth.BluetoothAdapter;
import android.bluetooth.BluetoothDevice;
import android.bluetooth.BluetoothManager;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.ConnectivityManager;
import android.net.LinkAddress;
import android.net.LinkProperties;
import android.net.Network;
import android.net.NetworkCapabilities;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.Switch;
import android.widget.TextView;

import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;

public final class MainActivity extends Activity {
    private static final int LOCATION_PERMISSION_REQUEST=1001,BLUETOOTH_PERMISSION_REQUEST=1002,CAMERA_PERMISSION_REQUEST=1003;
    private static final long DASHBOARD_PERIOD_MS=500;
    private static final String IMU_URL="http://127.0.0.1:8766/imu",LOCATION_URL="http://127.0.0.1:8766/location";
    private static final int BG=Color.rgb(6,16,24),SURFACE=Color.rgb(11,24,33),SURFACE_RAISED=Color.rgb(16,34,46),BORDER=Color.rgb(36,64,79),TEXT=Color.rgb(243,247,249),MUTED=Color.rgb(147,164,174),SILVER=Color.rgb(184,194,200),BLUE=Color.rgb(22,139,209),GREEN=Color.rgb(132,206,31),RED=Color.rgb(241,90,22);
    private final Handler dashboardHandler=new Handler(Looper.getMainLooper());
    private final Runnable dashboardRefresh=new Runnable(){@Override public void run(){refreshDashboard();refreshCameraStatus();dashboardHandler.postDelayed(this,DASHBOARD_PERIOD_MS);}};
    private final List<BluetoothDevice> pairedDevices=new ArrayList<>();
    private TextView status,remoteAccessStatus,bluetoothStatus,cameraStatus,cameraDetails,cameraEndpoint,accelerometerValue,linearAccelerationValue,gyroscopeValue,magnetometerValue,pressureValue,ambientLightValue,positionValue;
    private Spinner bluetoothDeviceSpinner; private Switch remoteAccessSwitch;
    private Button bridgeStartButton,bridgeStopButton,bluetoothStartButton,bluetoothStopButton,cameraStartButton,cameraStopButton,cameraLocalButton,cameraWifiButton,cameraCellularButton;
    private boolean bridgeRequestedRunning,bluetoothRequestedRunning,cameraRequestedRunning;
    private final BroadcastReceiver bluetoothStatusReceiver=new BroadcastReceiver(){@Override public void onReceive(Context context,Intent intent){if(!BluetoothSppBridgeService.ACTION_STATUS.equals(intent.getAction()))return;String state=intent.getStringExtra(BluetoothSppBridgeService.EXTRA_STATUS),message=intent.getStringExtra(BluetoothSppBridgeService.EXTRA_MESSAGE);if(message==null||message.isEmpty())message="Bluetooth bridge status unavailable";if(BluetoothSppBridgeService.STATUS_CONNECTING.equals(state)){bluetoothRequestedRunning=true;updateBluetoothButtons(true,false);bluetoothStatus.setText("●  "+message);bluetoothStatus.setTextColor(BLUE);}else if(BluetoothSppBridgeService.STATUS_CONNECTED.equals(state)){bluetoothRequestedRunning=true;updateBluetoothButtons(true,true);bluetoothStatus.setText("●  "+message);bluetoothStatus.setTextColor(GREEN);}else if(BluetoothSppBridgeService.STATUS_ERROR.equals(state)){bluetoothRequestedRunning=false;updateBluetoothButtons(false,false);bluetoothStatus.setText("●  "+message);bluetoothStatus.setTextColor(RED);}else if(BluetoothSppBridgeService.STATUS_STOPPED.equals(state)){bluetoothRequestedRunning=false;updateBluetoothButtons(false,false);bluetoothStatus.setText("●  "+message);bluetoothStatus.setTextColor(MUTED);}}};

    @Override protected void onCreate(Bundle savedInstanceState){super.onCreate(savedInstanceState);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);ScrollView scrollView=new ScrollView(this);scrollView.setBackgroundColor(BG);LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(10),dp(18),dp(10),dp(28));addBrandHeader(content);
        LinearLayout sensorCard=card();addSectionHeading(sensorCard,"SENSOR BRIDGE",BLUE,"Phone telemetry • HTTP 8766");status=statusPill("Bridge stopped",MUTED);sensorCard.addView(status);accelerometerValue=addSensorRow(sensorCard,"↗","Accelerometer","m/s²",BLUE);linearAccelerationValue=addSensorRow(sensorCard,"⇢","Linear acceleration","m/s²",GREEN);gyroscopeValue=addSensorRow(sensorCard,"↻","Gyroscope","rad/s",RED);magnetometerValue=addSensorRow(sensorCard,"⌖","Magnetometer","µT",BLUE);pressureValue=addSensorRow(sensorCard,"◉","Barometer","hPa",GREEN);ambientLightValue=addSensorRow(sensorCard,"☀","Ambient light","lux",BLUE);positionValue=addSensorRow(sensorCard,"◎","Position","lat / lon • accuracy • sats",RED);bridgeStartButton=actionButton("START BRIDGE",BLUE,v->startBridge());bridgeStopButton=actionButton("STOP",SURFACE_RAISED,v->stopBridge());sensorCard.addView(buttonRow(bridgeStartButton,bridgeStopButton));content.addView(sensorCard,cardParams());
        LinearLayout networkCard=card();addSectionHeading(networkCard,"REMOTE SENSOR ACCESS",BLUE,"Share sensor telemetry with devices on this network");remoteAccessSwitch=new Switch(this);remoteAccessSwitch.setText("Allow network clients");remoteAccessSwitch.setTextColor(TEXT);remoteAccessSwitch.setTextSize(15);remoteAccessSwitch.setPadding(dp(4),dp(4),dp(4),dp(8));boolean remoteEnabled=getSharedPreferences(SensorBridgeService.PREFERENCES,MODE_PRIVATE).getBoolean(SensorBridgeService.PREF_REMOTE_ACCESS,false);remoteAccessSwitch.setChecked(remoteEnabled);networkCard.addView(remoteAccessSwitch);remoteAccessStatus=statusPill("",remoteEnabled?GREEN:MUTED);networkCard.addView(remoteAccessStatus);updateRemoteAccessStatus();remoteAccessSwitch.setOnCheckedChangeListener((buttonView,isChecked)->setRemoteAccess(isChecked));content.addView(networkCard,cardParams());
        LinearLayout cameraCard=card();addSectionHeading(cameraCard,"CAMERA STREAM",RED,"Selectable camera • H.264 • 1280×720 • 30 FPS • HTTP 8767");cameraStatus=statusPill("Camera stopped",MUTED);cameraCard.addView(cameraStatus);CameraPreviewView cameraPreview=new CameraPreviewView(this);LinearLayout.LayoutParams previewParams=new LinearLayout.LayoutParams(-1,-2);previewParams.setMargins(dp(2),dp(2),dp(2),dp(8));cameraCard.addView(cameraPreview,previewParams);TextView routeLabel=text("VIDEO INTERFACE",11,MUTED);routeLabel.setTypeface(Typeface.DEFAULT,Typeface.BOLD);routeLabel.setLetterSpacing(.10f);routeLabel.setPadding(dp(2),dp(4),0,0);cameraCard.addView(routeLabel);cameraLocalButton=actionButton("LOCAL",SURFACE_RAISED,v->setCameraInterface(CameraStreamService.INTERFACE_LOCALHOST));cameraWifiButton=actionButton("WI-FI",SURFACE_RAISED,v->setCameraInterface(CameraStreamService.INTERFACE_WIFI));cameraCellularButton=actionButton("5G",SURFACE_RAISED,v->setCameraInterface(CameraStreamService.INTERFACE_CELLULAR));cameraCard.addView(buttonRow(cameraLocalButton,cameraWifiButton,cameraCellularButton));updateCameraInterfaceButtons();cameraDetails=text("Frames  —    Viewer  —    Preview  —",13,TEXT);cameraDetails.setTypeface(Typeface.MONOSPACE);cameraDetails.setPadding(dp(2),dp(5),0,dp(4));cameraCard.addView(cameraDetails);cameraEndpoint=text("Video endpoint  waiting for network",12,MUTED);cameraEndpoint.setTypeface(Typeface.MONOSPACE);cameraEndpoint.setPadding(dp(2),dp(2),0,dp(4));cameraCard.addView(cameraEndpoint);updateCameraEndpoint();cameraStartButton=actionButton("START CAMERA",RED,v->startCamera());cameraStopButton=actionButton("STOP",SURFACE_RAISED,v->stopCamera());cameraCard.addView(buttonRow(cameraStartButton,cameraStopButton));content.addView(cameraCard,cardParams());
        LinearLayout bluetoothCard=card();addSectionHeading(bluetoothCard,"BLUETOOTH SPP",GREEN,"Classic Bluetooth • RFCOMM transport");bluetoothStatus=statusPill("Tap REFRESH to load paired devices",MUTED);bluetoothCard.addView(bluetoothStatus);bluetoothDeviceSpinner=new Spinner(this);bluetoothDeviceSpinner.setBackground(rounded(SURFACE_RAISED,BORDER,10));bluetoothDeviceSpinner.setPadding(dp(10),0,dp(10),0);bluetoothCard.addView(bluetoothDeviceSpinner,new LinearLayout.LayoutParams(-1,dp(52)));bluetoothStartButton=actionButton("START SPP",BLUE,v->startBluetoothBridge());bluetoothStopButton=actionButton("STOP",SURFACE_RAISED,v->stopBluetoothBridge());bluetoothCard.addView(buttonRow(actionButton("REFRESH",BLUE,v->ensureBluetoothPermissionAndLoad()),bluetoothStartButton,bluetoothStopButton));TextView bluetoothHint=text("TCP endpoint  127.0.0.1:35000",12,MUTED);bluetoothHint.setTypeface(Typeface.MONOSPACE);bluetoothHint.setPadding(dp(2),dp(10),0,0);bluetoothCard.addView(bluetoothHint);content.addView(bluetoothCard,cardParams());TextView footer=text("OPENROADC0DE  •  BUILD "+BuildConfig.VERSION_NAME,11,MUTED);footer.setGravity(Gravity.CENTER);footer.setLetterSpacing(.12f);footer.setPadding(0,dp(8),0,0);content.addView(footer);scrollView.addView(content);setContentView(scrollView);registerReceiver(bluetoothStatusReceiver,new IntentFilter(BluetoothSppBridgeService.ACTION_STATUS),Context.RECEIVER_NOT_EXPORTED);}

    private void addBrandHeader(LinearLayout parent){LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.HORIZONTAL);brand.setGravity(Gravity.CENTER_VERTICAL);brand.setPadding(0,dp(4),0,dp(18));ImageView mark=new ImageView(this);mark.setImageResource(R.drawable.ic_openroadcode);mark.setScaleType(ImageView.ScaleType.CENTER_INSIDE);LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(dp(54),dp(54));mp.setMargins(0,0,dp(2),0);brand.addView(mark,mp);LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);LinearLayout titleRow=new LinearLayout(this);titleRow.setOrientation(LinearLayout.HORIZONTAL);addBrandWord(titleRow,"OPEN",BLUE);addBrandWord(titleRow," ROAD",RED);addBrandWord(titleRow," CODE",GREEN);words.addView(titleRow);TextView subtitle=text("ANDROID HARDWARE BRIDGE",11,SILVER);subtitle.setTypeface(Typeface.DEFAULT,Typeface.BOLD);subtitle.setLetterSpacing(.14f);words.addView(subtitle);brand.addView(words,new LinearLayout.LayoutParams(0,-2,1));ImageView badge=new ImageView(this);badge.setImageResource(R.drawable.ic_linux_sensor_bridge);badge.setScaleType(ImageView.ScaleType.CENTER_INSIDE);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(46),dp(46));bp.setMargins(dp(4),0,0,0);brand.addView(badge,bp);parent.addView(brand);}
    private void addBrandWord(LinearLayout row,String value,int color){TextView word=text(value,21,color);word.setTypeface(Typeface.DEFAULT,Typeface.BOLD);word.setLetterSpacing(.035f);row.addView(word);}private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(16),dp(12),dp(16));c.setBackground(rounded(SURFACE,BORDER,14));return c;}private LinearLayout.LayoutParams cardParams(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(14));return p;}private void addSectionHeading(LinearLayout p,String title,int accent,String sub){TextView h=text(title,18,TEXT);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setLetterSpacing(.08f);p.addView(h);TextView s=text(sub,12,accent);s.setTypeface(Typeface.DEFAULT,Typeface.BOLD);s.setPadding(0,dp(2),0,dp(10));p.addView(s);}private TextView statusPill(String value,int accent){TextView v=text("●  "+value,13,accent);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setPadding(dp(10),dp(8),dp(10),dp(8));v.setBackground(rounded(SURFACE_RAISED,BORDER,9));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(8));v.setLayoutParams(p);return v;}
    private TextView addSensorRow(LinearLayout parent,String icon,String name,String units,int accent){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,dp(7),0,dp(7));TextView iv=text(icon,22,accent);iv.setGravity(Gravity.CENTER);row.addView(iv,new LinearLayout.LayoutParams(dp(32),dp(44)));LinearLayout labels=new LinearLayout(this);labels.setOrientation(LinearLayout.VERTICAL);TextView nv=text(name,14,TEXT);nv.setTypeface(Typeface.DEFAULT,Typeface.BOLD);nv.setSingleLine(true);labels.addView(nv);labels.addView(text(units,11,MUTED));row.addView(labels,new LinearLayout.LayoutParams(0,-2,1.18f));TextView value=text("—",13,TEXT);value.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);value.setTypeface(Typeface.MONOSPACE);row.addView(value,new LinearLayout.LayoutParams(0,-2,1.62f));parent.addView(row);return value;}
    private Button actionButton(String label,int color,View.OnClickListener listener){Button b=new Button(this);b.setText(label);b.setTextColor(TEXT);b.setTextSize(11);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setLetterSpacing(.08f);b.setAllCaps(false);setButtonColor(b,color);b.setOnClickListener(listener);return b;}private void setButtonColor(Button b,int c){b.setBackground(rounded(c,c,9));}private void updateBridgeButtons(boolean r){bridgeStartButton.setText(r?"RUNNING":"START BRIDGE");setButtonColor(bridgeStartButton,r?SURFACE_RAISED:BLUE);setButtonColor(bridgeStopButton,r?RED:SURFACE_RAISED);}private void updateBluetoothButtons(boolean r,boolean c){bluetoothStartButton.setText(r?(c?"RUNNING":"CONNECTING"):"START SPP");setButtonColor(bluetoothStartButton,r?SURFACE_RAISED:BLUE);setButtonColor(bluetoothStopButton,r?RED:SURFACE_RAISED);}private void updateCameraButtons(boolean r,boolean s){cameraStartButton.setText(r?(s?"RUNNING":"STARTING"):"START CAMERA");setButtonColor(cameraStartButton,r?SURFACE_RAISED:RED);setButtonColor(cameraStopButton,r?RED:SURFACE_RAISED);}private LinearLayout buttonRow(Button...bs){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER);row.setPadding(0,dp(8),0,0);for(Button b:bs){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(46),1);p.setMargins(dp(3),0,dp(3),0);row.addView(b,p);}return row;}private TextView text(String v,float s,int c){TextView t=new TextView(this);t.setText(v);t.setTextSize(s);t.setTextColor(c);return t;}private GradientDrawable rounded(int f,int s,int r){GradientDrawable d=new GradientDrawable();d.setColor(f);d.setCornerRadius(dp(r));d.setStroke(dp(1),s);return d;}
    @Override protected void onResume(){super.onResume();updateRemoteAccessStatus();updateCameraEndpoint();dashboardHandler.post(dashboardRefresh);}@Override protected void onPause(){dashboardHandler.removeCallbacks(dashboardRefresh);super.onPause();}@Override protected void onDestroy(){unregisterReceiver(bluetoothStatusReceiver);super.onDestroy();}
    private JSONObject getJson(String url)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(250);c.setReadTimeout(250);c.setRequestMethod("GET");try(BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.UTF_8))){return new JSONObject(r.readLine());}finally{c.disconnect();}}
    private void refreshDashboard(){new Thread(()->{try{JSONObject imu=getJson(IMU_URL),pos=getJson(LOCATION_URL);runOnUiThread(()->{displaySample(imu);displayPosition(pos);});}catch(Exception ignored){runOnUiThread(()->{if(bridgeRequestedRunning){status.setText("●  Bridge starting…");status.setTextColor(BLUE);}else{status.setText("●  Bridge stopped");status.setTextColor(MUTED);}showUnavailable();});}},"orc-dashboard-refresh").start();}private void refreshCameraStatus(){new Thread(()->{try{String a=cameraAddress();if(a==null)throw new Exception();JSONObject c=getJson("http://"+a+":"+CameraStreamService.PORT+"/status");runOnUiThread(()->displayCameraStatus(c));}catch(Exception ignored){runOnUiThread(()->{if(!cameraRequestedRunning){cameraStatus.setText("●  Camera stopped");cameraStatus.setTextColor(MUTED);cameraDetails.setText("Frames  —    Viewer  —    Preview  —");updateCameraButtons(false,false);}});}},"orc-camera-status-refresh").start();}
    private void displaySample(JSONObject r){bridgeRequestedRunning=true;updateBridgeButtons(true);boolean ready=r.optBoolean("ready");status.setText(ready?"●  Bridge running • sensors ready":"●  Bridge running • waiting for sensors");status.setTextColor(ready?GREEN:BLUE);accelerometerValue.setText(vectorText(r.optJSONObject("acceleration_mps2")));linearAccelerationValue.setText(r.optBoolean("linear_acceleration_available")?vectorText(r.optJSONObject("linear_acceleration_mps2")):"Not available");gyroscopeValue.setText(vectorText(r.optJSONObject("angular_velocity_rad_s")));magnetometerValue.setText(r.optBoolean("magnetometer_available")?vectorText(r.optJSONObject("magnetic_field_uT")):"Not available");pressureValue.setText(r.optBoolean("pressure_available")?String.format(Locale.US,"%.2f",r.optDouble("pressure_hpa")):"Not available");ambientLightValue.setText(r.optBoolean("ambient_light_available")?String.format(Locale.US,"%.1f",r.optDouble("ambient_light_lux")):"Not available");}
    private void displayPosition(JSONObject r){if(!r.optBoolean("permission_granted")){positionValue.setText("Permission required");return;}if(!r.optBoolean("ready")){positionValue.setText(r.optBoolean("available")?"Waiting for fix":"Provider unavailable");return;}double a=r.optDouble("horizontal_accuracy_m",Double.NaN);int v=r.optInt("satellites_visible",-1),u=r.optInt("satellites_used_in_fix",-1);String sats=v<0?"sats —":(u>=0?"sats "+u+"/"+v:"sats "+v);positionValue.setText(String.format(Locale.US,"%.6f, %.6f\n%s  %s\n%s",r.optDouble("latitude"),r.optDouble("longitude"),Double.isNaN(a)?"accuracy —":String.format(Locale.US,"±%.1f m",a),r.optString("provider",""),sats));}
    private void displayCameraStatus(JSONObject r){String s=r.optString("state","unknown"),e=r.optString("error","");boolean client=r.optBoolean("client_connected",false),preview=r.optBoolean("preview_attached",false);long frames=r.optLong("encoded_frames",0);if("streaming".equals(s)){cameraRequestedRunning=true;updateCameraButtons(true,true);cameraStatus.setText("●  Camera "+r.optString("camera_id","?")+" streaming • 720p30 • "+interfaceLabel(r.optString("interface",currentCameraInterface())));cameraStatus.setTextColor(GREEN);}else if("starting".equals(s)){cameraRequestedRunning=true;updateCameraButtons(true,false);cameraStatus.setText("●  Camera starting…");cameraStatus.setTextColor(BLUE);}else if("error".equals(s)){cameraRequestedRunning=false;updateCameraButtons(false,false);cameraStatus.setText("●  Camera error • "+(e.isEmpty()?"unknown error":e));cameraStatus.setTextColor(RED);}else{cameraRequestedRunning=false;updateCameraButtons(false,false);cameraStatus.setText("●  Camera "+s);cameraStatus.setTextColor(MUTED);}cameraDetails.setText(String.format(Locale.US,"Frames  %,d    Viewer  %s    Preview  %s",frames,client?"connected":"none",preview?"on":"off"));updateCameraEndpoint();}
    private String vectorText(JSONObject v){if(v==null)return"—";return String.format(Locale.US,"x %+.2f  y %+.2f\nz %+.2f",v.optDouble("x"),v.optDouble("y"),v.optDouble("z"));}private void showUnavailable(){accelerometerValue.setText("—");linearAccelerationValue.setText("—");gyroscopeValue.setText("—");magnetometerValue.setText("—");pressureValue.setText("—");ambientLightValue.setText("—");positionValue.setText("—");}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
    private boolean hasLocationPermission(){return checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED;}private void startBridge(){bridgeRequestedRunning=true;updateBridgeButtons(true);if(!hasLocationPermission()){status.setText("●  Location permission required…");status.setTextColor(BLUE);requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},LOCATION_PERMISSION_REQUEST);return;}startSensorBridgeService();}private void startSensorBridgeService(){startForegroundService(new Intent(this,SensorBridgeService.class));status.setText("●  Bridge starting…");status.setTextColor(BLUE);}private void stopBridge(){bridgeRequestedRunning=false;updateBridgeButtons(false);stopService(new Intent(this,SensorBridgeService.class));status.setText("●  Bridge stopped");status.setTextColor(MUTED);showUnavailable();}private void startCamera(){if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},CAMERA_PERMISSION_REQUEST);return;}cameraRequestedRunning=true;updateCameraButtons(true,false);startForegroundService(new Intent(this,CameraStreamService.class));cameraStatus.setText("●  Camera starting…");cameraStatus.setTextColor(BLUE);}private void stopCamera(){cameraRequestedRunning=false;updateCameraButtons(false,false);stopService(new Intent(this,CameraStreamService.class));cameraStatus.setText("●  Camera stopped");cameraStatus.setTextColor(MUTED);cameraDetails.setText("Frames  —    Viewer  —    Preview  —");}
    private String currentCameraInterface(){return getSharedPreferences(CameraStreamService.PREFERENCES,MODE_PRIVATE).getString(CameraStreamService.PREF_INTERFACE,CameraStreamService.INTERFACE_WIFI);}private void setCameraInterface(String m){getSharedPreferences(CameraStreamService.PREFERENCES,MODE_PRIVATE).edit().putString(CameraStreamService.PREF_INTERFACE,m).apply();updateCameraInterfaceButtons();updateCameraEndpoint();if(cameraRequestedRunning){stopService(new Intent(this,CameraStreamService.class));cameraRequestedRunning=true;updateCameraButtons(true,false);startForegroundService(new Intent(this,CameraStreamService.class));cameraStatus.setText("●  Camera restarting on "+interfaceLabel(m)+"…");cameraStatus.setTextColor(BLUE);}}private void updateCameraInterfaceButtons(){if(cameraLocalButton==null)return;String m=currentCameraInterface();setButtonColor(cameraLocalButton,CameraStreamService.INTERFACE_LOCALHOST.equals(m)?BLUE:SURFACE_RAISED);setButtonColor(cameraWifiButton,CameraStreamService.INTERFACE_WIFI.equals(m)?BLUE:SURFACE_RAISED);setButtonColor(cameraCellularButton,CameraStreamService.INTERFACE_CELLULAR.equals(m)?BLUE:SURFACE_RAISED);}private String interfaceLabel(String m){if(CameraStreamService.INTERFACE_LOCALHOST.equals(m))return"LOCAL";if(CameraStreamService.INTERFACE_CELLULAR.equals(m))return"5G";return"WI-FI";}private String cameraAddress(){String m=currentCameraInterface();if(CameraStreamService.INTERFACE_LOCALHOST.equals(m))return"127.0.0.1";return findTransportAddress(CameraStreamService.INTERFACE_CELLULAR.equals(m)?NetworkCapabilities.TRANSPORT_CELLULAR:NetworkCapabilities.TRANSPORT_WIFI);}private String findTransportAddress(int t){ConnectivityManager cm=getSystemService(ConnectivityManager.class);if(cm==null)return null;for(Network n:cm.getAllNetworks()){NetworkCapabilities c=cm.getNetworkCapabilities(n);if(c==null||!c.hasTransport(t))continue;LinkProperties p=cm.getLinkProperties(n);if(p==null)continue;for(LinkAddress l:p.getLinkAddresses()){InetAddress a=l.getAddress();if(a instanceof Inet4Address&&!a.isLoopbackAddress())return a.getHostAddress();}}return null;}private void updateCameraEndpoint(){if(cameraEndpoint==null)return;String a=cameraAddress();cameraEndpoint.setText(a==null?interfaceLabel(currentCameraInterface())+" unavailable • port "+CameraStreamService.PORT:"Video  http://"+a+":"+CameraStreamService.PORT+"/video");cameraEndpoint.setTextColor(a==null?RED:GREEN);}
    private void setRemoteAccess(boolean e){getSharedPreferences(SensorBridgeService.PREFERENCES,MODE_PRIVATE).edit().putBoolean(SensorBridgeService.PREF_REMOTE_ACCESS,e).apply();updateRemoteAccessStatus();stopService(new Intent(this,SensorBridgeService.class));if(hasLocationPermission()){bridgeRequestedRunning=true;updateBridgeButtons(true);startSensorBridgeService();}else{bridgeRequestedRunning=false;updateBridgeButtons(false);}}private void updateRemoteAccessStatus(){if(remoteAccessStatus==null)return;boolean e=getSharedPreferences(SensorBridgeService.PREFERENCES,MODE_PRIVATE).getBoolean(SensorBridgeService.PREF_REMOTE_ACCESS,false);if(!e){remoteAccessStatus.setText("●  Disabled • localhost only • 127.0.0.1:"+SensorBridgeService.PORT);remoteAccessStatus.setTextColor(MUTED);return;}String a=findLanAddress();remoteAccessStatus.setText(a==null?"●  Enabled • waiting for a network address • port "+SensorBridgeService.PORT:"●  Enabled • http://"+a+":"+SensorBridgeService.PORT);remoteAccessStatus.setTextColor(a==null?BLUE:GREEN);}private String findLanAddress(){try{for(NetworkInterface n:Collections.list(NetworkInterface.getNetworkInterfaces())){if(!n.isUp()||n.isLoopback())continue;for(InetAddress a:Collections.list(n.getInetAddresses()))if(a instanceof Inet4Address&&!a.isLoopbackAddress())return a.getHostAddress();}}catch(Exception ignored){}return null;}
    private void ensureBluetoothPermissionAndLoad(){if(checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT},BLUETOOTH_PERMISSION_REQUEST);return;}loadPairedDevices();}private void loadPairedDevices(){if(checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){ensureBluetoothPermissionAndLoad();return;}BluetoothManager m=getSystemService(BluetoothManager.class);BluetoothAdapter a=m==null?null:m.getAdapter();pairedDevices.clear();List<String> labels=new ArrayList<>();if(a!=null)for(BluetoothDevice d:a.getBondedDevices()){pairedDevices.add(d);String n=d.getName();labels.add((n==null?"Unknown device":n)+"  •  "+d.getAddress());}ArrayAdapter<String> ad=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,labels){@Override public View getView(int p,View c,android.view.ViewGroup g){TextView v=(TextView)super.getView(p,c,g);v.setTextColor(TEXT);v.setTextSize(13);return v;}@Override public View getDropDownView(int p,View c,android.view.ViewGroup g){TextView v=(TextView)super.getDropDownView(p,c,g);v.setTextColor(TEXT);v.setBackgroundColor(SURFACE_RAISED);v.setPadding(dp(12),dp(12),dp(12),dp(12));return v;}};bluetoothDeviceSpinner.setAdapter(ad);if(!bluetoothRequestedRunning){bluetoothStatus.setText(labels.isEmpty()?"●  No paired classic Bluetooth devices":"●  "+labels.size()+" paired device(s) available");bluetoothStatus.setTextColor(labels.isEmpty()?RED:GREEN);}}private void startBluetoothBridge(){if(checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){ensureBluetoothPermissionAndLoad();return;}int p=bluetoothDeviceSpinner.getSelectedItemPosition();if(p<0||p>=pairedDevices.size()){bluetoothStatus.setText("●  Select a paired Bluetooth device first");bluetoothStatus.setTextColor(RED);return;}BluetoothDevice d=pairedDevices.get(p);Intent i=new Intent(this,BluetoothSppBridgeService.class);i.putExtra(BluetoothSppBridgeService.EXTRA_DEVICE_ADDRESS,d.getAddress());bluetoothRequestedRunning=true;updateBluetoothButtons(true,false);startForegroundService(i);bluetoothStatus.setText("●  Connecting to "+(d.getName()==null?d.getAddress():d.getName())+"…");bluetoothStatus.setTextColor(BLUE);}private void stopBluetoothBridge(){bluetoothRequestedRunning=false;updateBluetoothButtons(false,false);stopService(new Intent(this,BluetoothSppBridgeService.class));bluetoothStatus.setText("●  Bluetooth bridge stopped");bluetoothStatus.setTextColor(MUTED);}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==LOCATION_PERMISSION_REQUEST){if(hasLocationPermission()){bridgeRequestedRunning=true;updateBridgeButtons(true);startSensorBridgeService();}else{bridgeRequestedRunning=false;updateBridgeButtons(false);status.setText("●  Location permission required");status.setTextColor(RED);}}else if(r==BLUETOOTH_PERMISSION_REQUEST&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)loadPairedDevices();else if(r==CAMERA_PERMISSION_REQUEST){if(g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startCamera();else{cameraRequestedRunning=false;updateCameraButtons(false,false);cameraStatus.setText("●  Camera permission required");cameraStatus.setTextColor(RED);}}}
}
